name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Pick go_version
        id: go
        run: echo "version=$(grep golang .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go.outputs.version }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
